server:
  port: 8080
spring:
  application:
    name: agri-weather-backend
  mvc:
    charset: UTF-8
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

amap:
  key: 2a3aeb762e123e3a3943cdf379e7a1d7
  base: https://restapi.amap.com

# DeepSeek AI配置
deepseek:
  api:
    key: sk-7c3ffb5ef9a547cb89388a8dd8ae227c
    url: https://api.deepseek.com/chat/completions


